# Generated by Django 3.1.5 on 2021-01-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default-blog.png', null=True, upload_to='blog/thumbnails/'),
        ),
    ]
