# Generated by Django 3.1.5 on 2021-02-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210131_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visited',
            field=models.BigIntegerField(blank=True, default=0, null='True', verbose_name='visited'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/blog/default_blog.jpg', null=True, upload_to='blog/thumbnails/'),
        ),
    ]
